"""Comprehensive tests for SocialAutoPostService and Telegram Auto-Post Integration."""
import asyncio
import datetime as dt
import json
import os
import sys
import unittest
from unittest.mock import AsyncMock, MagicMock, patch

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from src.infrastructure.social_auto_post_service import SocialAutoPostService
from src.infrastructure.telegram_service import TelegramService


class TestSocialAutoPost(unittest.TestCase):

    def setUp(self):
        self.service = SocialAutoPostService()
        self.tg_service = TelegramService()

    def test_calculate_ai_schedule_times_ordering(self):
        """Verify AI calculates future peak engagement hours in correct chronological order."""
        now = dt.datetime(2026, 8, 16, 10, 0, 0, tzinfo=dt.timezone.utc)
        times = self.service.calculate_ai_schedule_times(
            clip_count=3,
            peak_hours_str="11:30, 15:00, 18:30, 20:30",
            start_time=now,
        )

        self.assertEqual(len(times), 3)
        # Verify chronological order
        self.assertLess(times[0], times[1])
        self.assertLess(times[1], times[2])
        # First slot should be today ~11:30 (with jitter)
        self.assertEqual(times[0].date(), now.date())
        self.assertIn(times[0].hour, [11, 12])

    def test_calculate_ai_schedule_times_next_day_wrap(self):
        """Verify late-night jobs wrap slots cleanly to the next day's peak hours."""
        now = dt.datetime(2026, 8, 16, 23, 0, 0, tzinfo=dt.timezone.utc)
        times = self.service.calculate_ai_schedule_times(
            clip_count=2,
            peak_hours_str="11:30, 15:00, 18:30, 20:30",
            start_time=now,
        )

        self.assertEqual(len(times), 2)
        # Should be on the next day
        tomorrow = now.date() + dt.timedelta(days=1)
        self.assertEqual(times[0].date(), tomorrow)
        self.assertIn(times[0].hour, [11, 12])

    def test_calculate_ai_schedule_times_10_clips_same_day_spread(self):
        """Verify 10 clips generated by autopilot are all scheduled on the SAME DAY at distinct spaced-out hours."""
        now = dt.datetime(2026, 8, 16, 8, 30, 0, tzinfo=dt.timezone.utc)
        times = self.service.calculate_ai_schedule_times(
            clip_count=10,
            start_time=now,
            same_day=True,
        )

        self.assertEqual(len(times), 10)
        # All 10 clips must be scheduled on the same day (today)
        for t in times:
            self.assertEqual(t.date(), now.date())

        # Each clip must have a distinct timestamp, strictly increasing
        for i in range(len(times) - 1):
            self.assertLess(times[i], times[i + 1])
            # Minimum 5 minutes spacing
            diff_mins = (times[i + 1] - times[i]).total_seconds() / 60.0
            self.assertGreaterEqual(diff_mins, 5.0)

    def test_extract_clip_caption_tiktok(self):
        """Verify TikTok caption extraction prioritizing tiktok key and adding tags."""
        clip = {
            "rank": 1,
            "hook": "Rahasia Mindset Juara",
            "captions": {
                "tiktok": "Tonton sampai habis trik rahasia ini!",
                "instagram": "Postingan Instagram khusus.",
            },
            "reason": "Topik sangat viral",
        }

        caption = self.service.extract_clip_caption(clip, platform="tiktok", include_hashtags=True)
        self.assertIn("Tonton sampai habis trik rahasia ini!", caption)
        self.assertIn("#fyp", caption)
        self.assertIn("#viral", caption)

    def test_extract_clip_caption_fallback_to_hook(self):
        """Verify caption falls back to hook when captions dict is empty."""
        clip = {
            "rank": 2,
            "hook": "5 Tips Finansial 2026",
            "reason": "Penting untuk pemula",
        }

        caption = self.service.extract_clip_caption(clip, platform="youtube", include_hashtags=True)
        self.assertIn("5 Tips Finansial 2026", caption)
        self.assertIn("#Shorts", caption)

    def test_telegram_settings_auto_post_fields(self):
        """Verify telegram_settings table handles auto_post options correctly."""
        updated = self.tg_service.update_settings({
            "is_enabled": True,
            "bot_token": "valid_token",
            "chat_id": "12345678",
            "auto_post_social": True,
            "auto_post_platforms": "tiktok,instagram",
            "auto_post_schedule_mode": "ai",
            "auto_post_interval_hours": 3,
            "auto_post_peak_hours": "12:00,18:00,21:00",
        })

        self.assertTrue(updated["auto_post_social"])
        self.assertEqual(updated["auto_post_platforms"], "tiktok,instagram")
        self.assertEqual(updated["auto_post_schedule_mode"], "ai")
        self.assertEqual(updated["auto_post_interval_hours"], 3)
        self.assertEqual(updated["auto_post_peak_hours"], "12:00,18:00,21:00")

    @patch("src.infrastructure.social_auto_post_service.repliz_post")
    @patch("src.infrastructure.social_auto_post_service.gdrive_uploader")
    @patch("src.infrastructure.social_auto_post_service.find_final_clip")
    @patch.object(SocialAutoPostService, "get_connected_accounts")
    def test_auto_schedule_job_clips_flow(self, mock_accounts, mock_find, mock_gdrive, mock_repliz_post):
        """Verify full auto_schedule_job_clips execution with mocked external services."""
        mock_accounts.return_value = [
            {"account_id": "acc_tt_123", "platform": "tiktok", "name": "My TikTok"},
            {"account_id": "acc_ig_456", "platform": "instagram", "name": "My Instagram"},
        ]
        mock_find.return_value = "/fake/path/clip_01_final.mp4"
        mock_gdrive.is_configured = True
        mock_gdrive.upload_video.return_value = {"direct_link": "https://drive.google.com/uc?id=123"}
        mock_repliz_post.return_value = {"_id": "sch_789", "status": "scheduled"}

        with patch("os.path.exists", return_value=True):
            clips = [
                {
                    "rank": 1,
                    "hook": "Cara Sukses di Usia Muda",
                    "captions": {"tiktok": "Wajib tahu tips ini!"},
                }
            ]

            async def _run():
                return await self.service.auto_schedule_job_clips(
                    job_id="job_test123",
                    clips=clips,
                    output_dir="/fake/path",
                    target_platforms=["tiktok", "instagram"],
                    schedule_mode="ai",
                    notify_telegram=False,
                )

            res = asyncio.run(_run())
            self.assertTrue(res["success"])
            self.assertEqual(res["scheduled_count"], 2)
            self.assertEqual(mock_repliz_post.call_count, 2)

    @patch("src.presentation.routes.social.publish.repliz_post")
    @patch("src.presentation.routes.social.publish.gdrive_uploader")
    @patch("src.application.video_generator.get_video_generator")
    def test_publish_video_generator_job(self, mock_get_vg, mock_gdrive, mock_repliz_post):
        """Verify publish_clip endpoint handles video_generator jobs with GDrive fallback when tunnel is unset."""
        from src.presentation.routes.social.publish import publish_clip, PublishRequest

        mock_vg = MagicMock()
        mock_job = MagicMock()
        mock_job.job_id = "vg_test_123"
        mock_job.output_path = "/tmp/video_gen/vg_test_123/final.mp4"
        mock_vg.get_job.return_value = mock_job
        mock_get_vg.return_value = mock_vg

        mock_gdrive.is_configured = True
        mock_gdrive.upload_video.return_value = {"direct_link": "https://drive.google.com/videogen"}
        mock_repliz_post.return_value = {"_id": "post_vg_1", "status": "scheduled"}

        with patch("os.path.exists", return_value=True), \
             patch("src.config.settings.AUTOCLIPER_PUBLIC_URL", ""), \
             patch.dict(os.environ, {"AUTOCLIPER_PUBLIC_URL": "", "PUBLIC_BACKEND_URL": ""}, clear=False), \
             patch("src.config.settings.REPLIZ_ACCESS_KEY", "key"), \
             patch("src.config.settings.REPLIZ_SECRET_KEY", "secret"):
            body = PublishRequest(
                jobId="vg_test_123",
                videoSource="video_generator",
                accountIds=["acc_tt_1", "acc_ig_2"],
                caption="AI Generated Video Content",
                title="AI Video Title",
                scheduleAt="2026-08-20T12:00:00Z",
                type="video",
            )

            res = asyncio.run(publish_clip(body, _user={"id": "admin"}))
            self.assertTrue(res["success"])
            self.assertEqual(res["count"], 2)
            mock_gdrive.upload_video.assert_called_once_with(
                "/tmp/video_gen/vg_test_123/final.mp4",
                filename="videogen_vg_test_123.mp4"
            )

    @patch("src.presentation.routes.social.publish.repliz_post")
    @patch("src.presentation.routes.social.publish.gdrive_uploader")
    @patch("src.application.video_generator.get_video_generator")
    def test_publish_video_generator_tunnel_flow(self, mock_get_vg, mock_gdrive, mock_repliz_post):
        """Verify publish_clip endpoint uses direct tunnel URL without uploading to Google Drive."""
        from src.presentation.routes.social.publish import publish_clip, PublishRequest

        mock_vg = MagicMock()
        mock_job = MagicMock()
        mock_job.job_id = "vg_test_123"
        mock_job.output_path = "/tmp/video_gen/vg_test_123/final.mp4"
        mock_vg.get_job.return_value = mock_job
        mock_get_vg.return_value = mock_vg

        mock_gdrive.is_configured = False
        mock_repliz_post.return_value = {"_id": "post_vg_tunnel", "status": "scheduled"}

        with patch("os.path.exists", return_value=True), \
             patch("src.config.settings.AUTOCLIPER_PUBLIC_URL", "https://my-live-tunnel.trycloudflare.com"), \
             patch("src.config.settings.REPLIZ_ACCESS_KEY", "key"), \
             patch("src.config.settings.REPLIZ_SECRET_KEY", "secret"):
            body = PublishRequest(
                jobId="vg_test_123",
                videoSource="video_generator",
                accountIds=["acc_tt_1"],
                caption="AI Generated Video Content",
                title="AI Video Title",
                scheduleAt="2026-08-20T12:00:00Z",
                type="video",
            )

            res = asyncio.run(publish_clip(body, _user={"id": "admin"}))
            self.assertTrue(res["success"])
            self.assertEqual(res["count"], 1)
            mock_gdrive.upload_video.assert_not_called()
            call_payload = mock_repliz_post.call_args[1]["json_body"]
            self.assertEqual(
                call_payload["medias"][0]["url"],
                "https://my-live-tunnel.trycloudflare.com/api/jobs/vg_test_123/clips/1/final",
            )

    @patch("src.presentation.routes.social.schedule.repliz_post")
    def test_create_schedule_endpoint(self, mock_repliz_post):
        """Verify create_schedule endpoint passes compliant Repliz payload."""
        from src.presentation.routes.social.schedule import create_schedule, ScheduleCreateRequest

        mock_repliz_post.return_value = {"scheduleId": "sch_abc123"}
        body = ScheduleCreateRequest(
            title="Judul Video Viral",
            description="Deskripsi postingan keren #fyp",
            topic="Tech News",
            type="video",
            medias=[{"url": "https://drive.google.com/test.mp4", "type": "video"}],
            accountId="680affa5ce12f2f72916f67e",
            scheduleAt="2026-08-28T15:00:00.000Z",
            additionalInfo={"isAiGenerated": True, "tags": ["Shorts", "Viral"]},
        )

        res = asyncio.run(create_schedule(body, _user={"id": "admin"}))
        self.assertEqual(res["scheduleId"], "sch_abc123")
        mock_repliz_post.assert_called_once()
        called_args = mock_repliz_post.call_args[1]["json_body"]
        self.assertEqual(called_args["title"], "Judul Video Viral")
        self.assertEqual(called_args["topic"], "Tech News")
        self.assertEqual(called_args["accountId"], "680affa5ce12f2f72916f67e")
        self.assertTrue(called_args["additionalInfo"]["isAiGenerated"])
        self.assertEqual(called_args["additionalInfo"]["tags"], ["Shorts", "Viral"])

    @patch("src.presentation.routes.social.schedule.repliz_get")
    def test_list_schedules_endpoint(self, mock_repliz_get):
        """Verify list_schedules passes query parameters to Repliz."""
        from src.presentation.routes.social.schedule import list_schedules

        mock_repliz_get.return_value = {
            "docs": [{"_id": "sch_1", "status": "pending"}],
            "totalDocs": 1,
            "totalPages": 1,
        }

        res = asyncio.run(list_schedules(
            page=1,
            limit=10,
            status="pending",
            account_ids="acc_1,acc_2",
            from_date="2026-08-01",
            to_date="2026-08-30",
            _user={"id": "admin"},
        ))

        self.assertEqual(len(res["docs"]), 1)
        mock_repliz_get.assert_called_once()
        params = mock_repliz_get.call_args[1]["params"]
        self.assertEqual(params["page"], 1)
        self.assertEqual(params["limit"], 10)
        self.assertEqual(params["status"], "pending")
        self.assertEqual(params["accountIds[0]"], "acc_1")
        self.assertEqual(params["accountIds[1]"], "acc_2")
        self.assertEqual(params["fromDate"], "2026-08-01")
        self.assertEqual(params["toDate"], "2026-08-30")

    @patch("src.presentation.routes.social.schedule.repliz_put")
    def test_retry_schedule_endpoint(self, mock_repliz_put):
        """Verify retry_schedule calls Repliz /retry endpoint."""
        from src.presentation.routes.social.schedule import retry_schedule

        mock_repliz_put.return_value = {"success": True, "message": "Schedule retried"}
        res = asyncio.run(retry_schedule("sch_123", _user={"id": "admin"}))
        self.assertTrue(res["success"])
        mock_repliz_put.assert_called_once_with("/public/schedule/sch_123/retry", json_body={})

    def test_get_supported_post_type_platform_rules(self):
        """Verify post type is normalized according to Repliz supported post types table."""
        from src.presentation.routes.social.publish import get_supported_post_type

        # TikTok does NOT support 'reel', must be 'video'
        self.assertEqual(get_supported_post_type("reel", platform="tiktok"), "video")
        self.assertEqual(get_supported_post_type("video", platform="tiktok"), "video")

        # Instagram does NOT support 'reel' in Repliz API, must be 'video'
        self.assertEqual(get_supported_post_type("reel", platform="instagram"), "video")
        self.assertEqual(get_supported_post_type("story", platform="instagram"), "story")

        # Facebook supports 'reel'
        self.assertEqual(get_supported_post_type("reel", platform="facebook"), "reel")
        self.assertEqual(get_supported_post_type("video", platform="facebook"), "video")

        # YouTube only supports 'video'
        self.assertEqual(get_supported_post_type("reel", platform="youtube"), "video")
        self.assertEqual(get_supported_post_type("video", platform="youtube"), "video")

    @patch("src.presentation.routes.social.schedule._get_user_account_ids")
    @patch("src.presentation.routes.social.schedule.repliz_get")
    def test_regular_user_isolation_schedules(self, mock_repliz_get, mock_get_account_ids):
        """Verify non-superadmin only sees schedules belonging to their own accounts."""
        from src.presentation.routes.social.schedule import list_schedules

        # Regular user with account 'acc_user1'
        mock_get_account_ids.return_value = ["acc_user1"]
        mock_repliz_get.return_value = {
            "docs": [
                {"_id": "sch_1", "accountId": "acc_user1", "status": "pending"},
                {"_id": "sch_2", "accountId": "acc_other_user", "status": "pending"},
            ],
            "totalDocs": 2,
            "totalPages": 1,
        }

        res = asyncio.run(list_schedules(
            page=1,
            limit=10,
            _user={"id": 42, "is_superadmin": False, "role": "user"},
        ))

        # Only sch_1 belongs to user's accounts
        self.assertEqual(len(res["docs"]), 1)
        self.assertEqual(res["docs"][0]["_id"], "sch_1")
        self.assertEqual(res["totalDocs"], 1)

    @patch("src.presentation.routes.social.schedule._get_user_account_ids")
    def test_regular_user_without_accounts_gets_empty_schedules(self, mock_get_account_ids):
        """Verify non-superadmin with no connected accounts gets empty response without calling Repliz."""
        from src.presentation.routes.social.schedule import list_schedules

        mock_get_account_ids.return_value = []

        res = asyncio.run(list_schedules(
            page=1,
            limit=10,
            _user={"id": 99, "is_superadmin": False, "role": "user"},
        ))

        self.assertEqual(res["data"]["totalDocs"], 0)
        self.assertEqual(len(res["data"]["docs"]), 0)


if __name__ == "__main__":
    unittest.main()


