"""Scene Graph — Structured timeline representation for video composition.

The Scene Graph replaces the linear file-by-file pipeline output with a
structured, validated, editable representation of all visual and audio events.

Key concepts:
- Layers: visual stacking order (video base → broll → vfx → text → subtitle)
- Events: timed occurrences on a layer (text appearing, broll overlay, zoom, etc.)
- Constraints: rules that the graph must satisfy (no overlap, safe zones, etc.)
- Dependencies: event B cannot start before event A finishes

The scene graph is:
1. Generated by the pipeline (from Gemini analysis + Whisper + prosody)
2. Validated before render
3. Stored in database for editing/re-render
4. Consumed by the render engine (FFmpeg or Remotion)
"""
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Optional
import json
import logging

logger = logging.getLogger(__name__)


class LayerType(str, Enum):
    BASE_VIDEO = "base_video"
    BROLL = "broll"
    HOOK = "hook"
    VFX = "vfx"
    TYPOGRAPHY = "typography"
    SUBTITLE = "subtitle"
    AUDIO_MUSIC = "audio_music"
    AUDIO_SFX = "audio_sfx"
    COLOR_GRADE = "color_grade"


class EventType(str, Enum):
    # Visual events
    HOOK_TEXT = "hook_text"
    BROLL_OVERLAY = "broll_overlay"
    SUBTITLE_LINE = "subtitle_line"
    ZOOM_PUNCH = "zoom_punch"
    CAMERA_SHAKE = "camera_shake"
    COLOR_SHIFT = "color_shift"
    # Audio events
    MUSIC_BED = "music_bed"
    SFX_HIT = "sfx_hit"
    DUCK_TRIGGER = "duck_trigger"


@dataclass
class SceneLayer:
    """A layer in the composition stack."""
    id: str
    type: LayerType
    z_index: int
    blend_mode: str = "normal"  # normal / overlay / multiply / screen
    opacity: float = 1.0
    safe_zone: bool = False  # If true, content respects safe margins


@dataclass
class SceneEvent:
    """A timed event on a specific layer."""
    id: str
    layer_id: str
    event_type: EventType
    start: float
    end: float
    # Rendering parameters
    preset: str = ""
    params: dict = field(default_factory=dict)
    # Relationships
    dependencies: list[str] = field(default_factory=list)
    triggered_by: Optional[str] = None  # e.g., "audio_peak_at_12.5"
    # Metadata
    source: str = ""  # "gemini" / "prosody" / "whisper" / "user"


@dataclass
class SceneConstraint:
    """A constraint that the scene graph must satisfy."""
    rule: str
    value: Any
    severity: str = "warn"  # "error" (blocks render) / "warn" (log only)


@dataclass
class SceneGraph:
    """Complete scene graph for one clip."""
    clip_rank: int
    duration: float
    layers: list[SceneLayer] = field(default_factory=list)
    events: list[SceneEvent] = field(default_factory=list)
    constraints: list[SceneConstraint] = field(default_factory=list)
    # Metadata
    version: str = "2.0"
    creative_direction: dict = field(default_factory=dict)

    @classmethod
    def create_default(cls, clip_rank: int, duration: float) -> "SceneGraph":
        """Create a scene graph with default layer stack."""
        return cls(
            clip_rank=clip_rank,
            duration=duration,
            layers=[
                SceneLayer(id="L1_video", type=LayerType.BASE_VIDEO, z_index=1),
                SceneLayer(id="L2_broll", type=LayerType.BROLL, z_index=2),
                SceneLayer(id="L3_hook", type=LayerType.HOOK, z_index=3),
                SceneLayer(id="L4_vfx", type=LayerType.VFX, z_index=4),
                SceneLayer(id="L5_subtitle", type=LayerType.SUBTITLE, z_index=5, safe_zone=True),
                SceneLayer(id="L6_audio", type=LayerType.AUDIO_MUSIC, z_index=0),
            ],
            constraints=[
                SceneConstraint(rule="max_broll_duration", value=4.0),
                SceneConstraint(rule="min_subtitle_gap", value=0.1),
                SceneConstraint(rule="no_text_overlap", value=True),
                SceneConstraint(rule="hook_max_duration", value=3.5),
            ],
        )

    def add_event(self, event: SceneEvent) -> None:
        """Add an event to the graph."""
        self.events.append(event)

    def get_events_for_layer(self, layer_id: str) -> list[SceneEvent]:
        """Get all events on a specific layer, sorted by start time."""
        return sorted(
            [e for e in self.events if e.layer_id == layer_id],
            key=lambda e: e.start,
        )

    def to_dict(self) -> dict:
        """Serialize to dict for JSON storage."""
        return {
            "version": self.version,
            "clip_rank": self.clip_rank,
            "duration": self.duration,
            "creative_direction": self.creative_direction,
            "layers": [
                {"id": l.id, "type": l.type.value, "z_index": l.z_index,
                 "blend_mode": l.blend_mode, "opacity": l.opacity}
                for l in self.layers
            ],
            "events": [
                {"id": e.id, "layer_id": e.layer_id, "event_type": e.event_type.value,
                 "start": e.start, "end": e.end, "preset": e.preset,
                 "params": e.params, "source": e.source}
                for e in self.events
            ],
        }

    @classmethod
    def from_dict(cls, data: dict) -> "SceneGraph":
        """Deserialize from dict."""
        graph = cls(
            clip_rank=data.get("clip_rank", 0),
            duration=data.get("duration", 0),
            version=data.get("version", "2.0"),
            creative_direction=data.get("creative_direction", {}),
        )
        for l in data.get("layers", []):
            graph.layers.append(SceneLayer(
                id=l["id"], type=LayerType(l["type"]),
                z_index=l.get("z_index", 0),
                blend_mode=l.get("blend_mode", "normal"),
                opacity=l.get("opacity", 1.0),
            ))
        for e in data.get("events", []):
            graph.events.append(SceneEvent(
                id=e["id"], layer_id=e["layer_id"],
                event_type=EventType(e["event_type"]),
                start=e["start"], end=e["end"],
                preset=e.get("preset", ""),
                params=e.get("params", {}),
                source=e.get("source", ""),
            ))
        return graph


# ─── Scene Graph Composer ─────────────────────────────────────────────────────

class SceneGraphComposer:
    """Composes a scene graph from pipeline analysis results.

    Takes:
    - Clip metadata (start, end, hook)
    - Whisper words (for subtitle events)
    - B-roll suggestions (for overlay events)
    - Prosody analysis (for VFX triggers at energy peaks / silence gaps)
    - Creative direction (for consistent styling)

    Produces:
    - Validated SceneGraph ready for rendering
    """

    def compose(
        self,
        clip_rank: int,
        clip_duration: float,
        hook_text: str,
        words: list[dict],
        broll_suggestions: list[dict],
        prosody: Optional[Any] = None,
        creative_direction: Optional[dict] = None,
    ) -> SceneGraph:
        """Compose a complete scene graph for one clip."""
        graph = SceneGraph.create_default(clip_rank, clip_duration)
        graph.creative_direction = creative_direction or {}

        event_counter = 0

        def next_id() -> str:
            nonlocal event_counter
            event_counter += 1
            return f"evt_{clip_rank:02d}_{event_counter:03d}"

        # ─── Hook events (first 3 seconds) ─────────────────────────────────
        if hook_text:
            graph.add_event(SceneEvent(
                id=next_id(),
                layer_id="L3_hook",
                event_type=EventType.HOOK_TEXT,
                start=0.0,
                end=3.0,
                preset="fade_scale",
                params={"text": hook_text, "font_size": 52, "overlay_opacity": 0.6},
                source="gemini",
            ))

        # ─── B-roll overlay events ──────────────────────────────────────────
        for broll in broll_suggestions:
            at_time = broll.get("at_time", 0)
            duration = broll.get("duration", 2.0)
            graph.add_event(SceneEvent(
                id=next_id(),
                layer_id="L2_broll",
                event_type=EventType.BROLL_OVERLAY,
                start=at_time,
                end=at_time + duration,
                preset=broll.get("template", "word_pop_typography"),
                params={"keyword": broll.get("keyword", ""), "duration": duration},
                source="gemini",
            ))

        # ─── Subtitle events (word-by-word lines) ──────────────────────────
        if words:
            lines = self._group_words_to_lines(words, max_per_line=4)
            for line in lines:
                line_start = line[0]["start"] + 3.0  # offset for hook
                line_end = line[-1]["end"] + 3.0
                line_text = " ".join(w["word"] for w in line)
                graph.add_event(SceneEvent(
                    id=next_id(),
                    layer_id="L5_subtitle",
                    event_type=EventType.SUBTITLE_LINE,
                    start=line_start,
                    end=line_end,
                    params={"text": line_text, "words": line},
                    source="whisper",
                ))

        # ─── Prosody-driven VFX events ──────────────────────────────────────
        if prosody:
            # Add zoom punch at energy peaks
            peaks = getattr(prosody, "energy_peaks", [])
            for peak in peaks[:5]:  # Max 5 VFX events
                if peak.time > 3.0:  # Don't interfere with hook
                    graph.add_event(SceneEvent(
                        id=next_id(),
                        layer_id="L4_vfx",
                        event_type=EventType.ZOOM_PUNCH,
                        start=peak.time,
                        end=peak.time + 0.3,
                        preset="punch_zoom",
                        params={"intensity": peak.intensity, "direction": "in"},
                        triggered_by=f"energy_peak_at_{peak.time}",
                        source="prosody",
                    ))

        # ─── Audio events ───────────────────────────────────────────────────
        graph.add_event(SceneEvent(
            id=next_id(),
            layer_id="L6_audio",
            event_type=EventType.MUSIC_BED,
            start=0.0,
            end=clip_duration,
            preset="background_music",
            params={"mood": creative_direction.get("music_mood", "energetic") if creative_direction else "energetic"},
            source="system",
        ))

        return graph

    def _group_words_to_lines(self, words: list[dict], max_per_line: int = 4) -> list[list[dict]]:
        """Group words into subtitle lines."""
        lines = []
        current = []
        for w in words:
            current.append(w)
            if len(current) >= max_per_line:
                lines.append(current)
                current = []
        if current:
            lines.append(current)
        return lines


# ─── Scene Graph Validator ────────────────────────────────────────────────────

class SceneGraphValidator:
    """Validates a scene graph against its constraints."""

    def validate(self, graph: SceneGraph) -> list[str]:
        """Validate graph, return list of issues (empty = valid)."""
        issues = []

        # Check constraint: no_text_overlap
        subtitle_events = graph.get_events_for_layer("L5_subtitle")
        for i in range(len(subtitle_events) - 1):
            if subtitle_events[i].end > subtitle_events[i + 1].start:
                issues.append(
                    f"Subtitle overlap: '{subtitle_events[i].id}' ends at "
                    f"{subtitle_events[i].end:.2f} but next starts at "
                    f"{subtitle_events[i + 1].start:.2f}"
                )

        # Check constraint: max_broll_duration
        broll_events = graph.get_events_for_layer("L2_broll")
        for e in broll_events:
            duration = e.end - e.start
            if duration > 4.0:
                issues.append(f"B-roll '{e.id}' too long: {duration:.1f}s > 4.0s")

        # Check constraint: hook_max_duration
        hook_events = graph.get_events_for_layer("L3_hook")
        for e in hook_events:
            if e.end > 3.5:
                issues.append(f"Hook '{e.id}' exceeds 3.5s: ends at {e.end:.1f}s")

        # Check: events don't exceed clip duration
        for e in graph.events:
            if e.end > graph.duration + 0.5:  # 0.5s tolerance
                issues.append(f"Event '{e.id}' exceeds clip duration: {e.end:.1f} > {graph.duration:.1f}")

        # Check: b-roll doesn't overlap with hook
        for broll in broll_events:
            if broll.start < 3.0:
                issues.append(f"B-roll '{broll.id}' overlaps with hook zone (starts at {broll.start:.1f}s)")

        return issues
