"""Subtitle style presets for FFmpeg and Skia engines.

Each style has a truly distinct visual identity — not just color/font swaps.
Differences: layout, animation mode, text transform, bg shape, positioning, effects.
"""

# ─── FFmpeg Subtitle Styles (drawtext-based) ──────────────────────────────────
# Each style produces fundamentally different visual output via drawtext filters.

FFMPEG_STYLES = {
    "classic_karaoke": {
        "id": "classic_karaoke",
        "name": "Classic Karaoke",
        "description": "Standard word-by-word highlight. Clean white text, active word turns yellow.",
        "category": "karaoke",
        "font_family": "Poppins",
        "font_weight": "Bold",
        "font_size": 38,
        "color": "#FFFFFF",
        "highlight_color": "#FFCC00",
        "stroke_color": "#000000",
        "stroke_width": 3,
        "shadow_color": "black@0.6",
        "shadow_x": 2,
        "shadow_y": 2,
        "background_opacity": 0.0,
        "background_color": "",
        "background_radius": 0,
        "position": "bottom",
        "padding_bottom": 120,
        "uppercase": False,
        "max_words_per_line": 3,
        "line_transition": "karaoke",
        "gradient_enabled": False,
        "gradient_colors": [],
    },
    "hormozi_pop": {
        "id": "hormozi_pop",
        "name": "Hormozi Pop",
        "description": "Bold center-screen word pop. Bright lime active word with thick black stroke.",
        "category": "impact",
        "font_family": "Montserrat",
        "font_weight": "Black",
        "font_size": 52,
        "color": "#FFFFFF",
        "highlight_color": "#00FF66",
        "stroke_color": "#000000",
        "stroke_width": 5,
        "shadow_color": "black@0.9",
        "shadow_x": 3,
        "shadow_y": 3,
        "background_opacity": 0.0,
        "background_color": "",
        "background_radius": 0,
        "position": "center",
        "padding_bottom": 0,
        "uppercase": True,
        "max_words_per_line": 2,
        "line_transition": "word_pop",
        "gradient_enabled": False,
        "gradient_colors": [],
    },
    "devon_clean": {
        "id": "devon_clean",
        "name": "Devon Clean",
        "description": "Subtle rounded dark pill background, crisp white typography with cyan active pop.",
        "category": "clean",
        "font_family": "Inter",
        "font_weight": "Bold",
        "font_size": 32,
        "color": "#E2E8F0",
        "highlight_color": "#00F0FF",
        "stroke_color": "",
        "stroke_width": 0,
        "shadow_color": "black@0.5",
        "shadow_x": 0,
        "shadow_y": 2,
        "background_opacity": 0.75,
        "background_color": "#0F172A",
        "background_radius": 14,
        "position": "bottom",
        "padding_bottom": 130,
        "uppercase": False,
        "max_words_per_line": 4,
        "line_transition": "karaoke",
        "gradient_enabled": False,
        "gradient_colors": [],
    },
    "podcast_dialogue": {
        "id": "podcast_dialogue",
        "name": "Podcast Dialogue",
        "description": "Dark charcoal dialogue pill with emerald active speaker highlight for interviews.",
        "category": "clean",
        "font_family": "Plus Jakarta Sans",
        "font_weight": "Bold",
        "font_size": 32,
        "color": "#E2E8F0",
        "highlight_color": "#10B981",
        "stroke_color": "",
        "stroke_width": 0,
        "shadow_color": "black@0.6",
        "shadow_x": 0,
        "shadow_y": 3,
        "background_opacity": 0.85,
        "background_color": "#18181B",
        "background_radius": 20,
        "position": "bottom",
        "padding_bottom": 130,
        "uppercase": False,
        "max_words_per_line": 4,
        "line_transition": "karaoke",
        "gradient_enabled": False,
        "gradient_colors": [],
    },
    "neon_glow": {
        "id": "neon_glow",
        "name": "Neon Glow",
        "description": "Glowing neon text on dark. Heavy border glow simulates neon tube effect.",
        "category": "glow",
        "font_family": "Montserrat",
        "font_weight": "Black",
        "font_size": 42,
        "color": "#00FFAA",
        "highlight_color": "#FF00FF",
        "stroke_color": "#00FFAA",
        "stroke_width": 4,
        "shadow_color": "#00FFAA@0.8",
        "shadow_x": 0,
        "shadow_y": 0,
        "background_opacity": 0.7,
        "background_color": "#000000",
        "background_radius": 0,
        "position": "center",
        "padding_bottom": 0,
        "uppercase": True,
        "max_words_per_line": 2,
        "line_transition": "word_pop",
        "gradient_enabled": False,
        "gradient_colors": [],
    },
    "bold_impact": {
        "id": "bold_impact",
        "name": "Bold Impact",
        "description": "Massive uppercase text, center screen. Impact-style with thick black outline.",
        "category": "impact",
        "font_family": "Anton",
        "font_weight": "Regular",
        "font_size": 60,
        "color": "#FFFFFF",
        "highlight_color": "#FF3333",
        "stroke_color": "#000000",
        "stroke_width": 5,
        "shadow_color": "black@0.9",
        "shadow_x": 3,
        "shadow_y": 3,
        "background_opacity": 0.0,
        "background_color": "",
        "background_radius": 0,
        "position": "center",
        "padding_bottom": 0,
        "uppercase": True,
        "max_words_per_line": 2,
        "line_transition": "word_pop",
        "gradient_enabled": False,
        "gradient_colors": [],
    },
    "cinematic_bar": {
        "id": "cinematic_bar",
        "name": "Cinematic Bar",
        "description": "Full-width dark bar at bottom. Uppercase condensed font. Film subtitle style.",
        "category": "cinematic",
        "font_family": "Oswald",
        "font_weight": "Medium",
        "font_size": 28,
        "color": "#E0E0E0",
        "highlight_color": "#FFD700",
        "stroke_color": "",
        "stroke_width": 0,
        "shadow_color": "",
        "shadow_x": 0,
        "shadow_y": 0,
        "background_opacity": 0.75,
        "background_color": "#1A1A1A",
        "background_radius": 0,
        "position": "bottom",
        "padding_bottom": 60,
        "uppercase": True,
        "max_words_per_line": 6,
        "line_transition": "line_reveal",
        "gradient_enabled": False,
        "gradient_colors": [],
    },
    "fire_emphasis": {
        "id": "fire_emphasis",
        "name": "Fire Emphasis",
        "description": "Big keyword pops in orange-red, small context words below. Energy/hype content.",
        "category": "emphasis",
        "font_family": "Bebas Neue",
        "font_weight": "Regular",
        "font_size": 36,
        "color": "#FFFFFF",
        "highlight_color": "#FF4500",
        "stroke_color": "#000000",
        "stroke_width": 4,
        "shadow_color": "#FF4500@0.5",
        "shadow_x": 0,
        "shadow_y": 4,
        "background_opacity": 0.0,
        "background_color": "",
        "background_radius": 0,
        "position": "bottom",
        "padding_bottom": 100,
        "uppercase": True,
        "max_words_per_line": 3,
        "line_transition": "emphasis",
        "gradient_enabled": False,
        "gradient_colors": [],
    },
    "glass_blur": {
        "id": "glass_blur",
        "name": "Glass Blur",
        "description": "Frosted glass background effect. White text on translucent blurred panel.",
        "category": "glass",
        "font_family": "Inter",
        "font_weight": "SemiBold",
        "font_size": 30,
        "color": "#FFFFFF",
        "highlight_color": "#60A5FA",
        "stroke_color": "",
        "stroke_width": 0,
        "shadow_color": "white@0.2",
        "shadow_x": 0,
        "shadow_y": 1,
        "background_opacity": 0.45,
        "background_color": "#FFFFFF",
        "background_radius": 16,
        "position": "bottom",
        "padding_bottom": 130,
        "uppercase": False,
        "max_words_per_line": 4,
        "line_transition": "karaoke",
        "gradient_enabled": False,
        "gradient_colors": [],
    },
    "tech_mono": {
        "id": "tech_mono",
        "name": "Tech Monospace",
        "description": "Clean monospace typography in dark terminal box with cyan active word highlight.",
        "category": "tech",
        "font_family": "Space Grotesk",
        "font_weight": "Bold",
        "font_size": 30,
        "color": "#94A3B8",
        "highlight_color": "#06B6D4",
        "stroke_color": "",
        "stroke_width": 0,
        "shadow_color": "black@0.6",
        "shadow_x": 0,
        "shadow_y": 2,
        "background_opacity": 0.8,
        "background_color": "#090D16",
        "background_radius": 8,
        "position": "bottom",
        "padding_bottom": 120,
        "uppercase": True,
        "max_words_per_line": 3,
        "line_transition": "word_pop",
        "gradient_enabled": False,
        "gradient_colors": [],
    },
    "gold_luxury": {
        "id": "gold_luxury",
        "name": "Gold Luxury",
        "description": "Champagne gold serif typography with soft ambient drop shadow for luxury/documentary.",
        "category": "cinematic",
        "font_family": "Playfair Display",
        "font_weight": "Bold",
        "font_size": 34,
        "color": "#CBD5E1",
        "highlight_color": "#FCD34D",
        "stroke_color": "#000000",
        "stroke_width": 2,
        "shadow_color": "black@0.7",
        "shadow_x": 0,
        "shadow_y": 3,
        "background_opacity": 0.0,
        "background_color": "",
        "background_radius": 0,
        "position": "bottom",
        "padding_bottom": 120,
        "uppercase": False,
        "max_words_per_line": 3,
        "line_transition": "word_pop",
        "gradient_enabled": False,
        "gradient_colors": [],
    },
    "minimal_lower": {
        "id": "minimal_lower",
        "name": "Minimal Lower",
        "description": "Clean lowercase documentary style at the bottom of the screen.",
        "category": "minimal",
        "font_family": "Inter",
        "font_weight": "Medium",
        "font_size": 24,
        "color": "#CCCCCC",
        "highlight_color": "#FFFFFF",
        "stroke_color": "",
        "stroke_width": 0,
        "shadow_color": "black@0.5",
        "shadow_x": 0,
        "shadow_y": 2,
        "background_opacity": 0.0,
        "background_color": "",
        "background_radius": 0,
        "position": "bottom",
        "padding_bottom": 50,
        "uppercase": False,
        "max_words_per_line": 5,
        "line_transition": "line_reveal",
        "gradient_enabled": False,
        "gradient_colors": [],
    },
}

# ─── Skia Subtitle Styles (CanvasKit GPU-rendered) ────────────────────────────
# Skia supports: gradients, rounded rects, blur, glow, multi-color text, shadows.
# Each produces a PNG frame overlay composited onto video via FFmpeg.

SKIA_STYLES = {
    "glassmorphism": {
        "id": "glassmorphism",
        "name": "Glassmorphism",
        "description": "Real frosted glass: backdrop blur + semi-transparent rounded card + inner border glow.",
        "category": "glass",
        "font_family": "Inter",
        "font_weight": "SemiBold",
        "font_size": 32,
        "text_fill": "solid",
        "text_color": "#FFFFFF",
        "highlight_fill": "solid",
        "highlight_color": "#38BDF8",
        "stroke": None,
        "shadow": None,
        "background": {
            "type": "glassmorphism",
            "blur_radius": 24,
            "bg_color": "#1E293B",
            "bg_opacity": 0.45,
            "border_radius": 16,
            "border_color": "#FFFFFF",
            "border_opacity": 0.2,
            "border_width": 1.5,
            "padding_x": 24,
            "padding_y": 12,
            "inner_shadow": {"color": "#FFFFFF", "opacity": 0.05, "blur": 4, "offset_y": -1},
        },
        "position_y_pct": 78,
        "uppercase": False,
        "max_words_per_line": 4,
        "line_transition": "karaoke",
        "per_char_transform": None,
    },
    "clean_editorial": {
        "id": "clean_editorial",
        "name": "Clean Editorial",
        "description": "Minimalist Swiss typography with a sleek slate pill and crisp word-by-word active highlight.",
        "category": "clean",
        "font_family": "Inter",
        "font_weight": "SemiBold",
        "font_size": 34,
        "text_fill": "solid",
        "text_color": "#CBD5E1",
        "highlight_fill": "solid",
        "highlight_color": "#38BDF8",
        "stroke": None,
        "shadow": {"color": "#000000", "blur": 8, "offset_x": 0, "offset_y": 2, "opacity": 0.45},
        "background": {
            "type": "pill",
            "bg_color": "#0F172A",
            "bg_opacity": 0.7,
            "border_radius": 12,
            "border_color": "rgba(255,255,255,0.15)",
            "border_width": 1,
            "padding_x": 18,
            "padding_y": 10,
        },
        "position_y_pct": 80,
        "uppercase": False,
        "max_words_per_line": 4,
        "line_transition": "karaoke",
        "per_char_transform": None,
    },
    "podcast_pro": {
        "id": "podcast_pro",
        "name": "Podcast Pro",
        "description": "Dialogue-optimized floating dark capsule with emerald active speaker highlight.",
        "category": "clean",
        "font_family": "Plus Jakarta Sans",
        "font_weight": "Bold",
        "font_size": 32,
        "text_fill": "solid",
        "text_color": "#E2E8F0",
        "highlight_fill": "solid",
        "highlight_color": "#10B981",
        "stroke": None,
        "shadow": {"color": "#000000", "blur": 10, "offset_x": 0, "offset_y": 3, "opacity": 0.6},
        "background": {
            "type": "pill",
            "bg_color": "#18181B",
            "bg_opacity": 0.85,
            "border_radius": 999,
            "border_color": "rgba(255,255,255,0.12)",
            "border_width": 1.2,
            "padding_x": 20,
            "padding_y": 10,
        },
        "position_y_pct": 78,
        "uppercase": False,
        "max_words_per_line": 4,
        "line_transition": "karaoke",
        "per_char_transform": None,
    },
    "kinetic_word_box": {
        "id": "kinetic_word_box",
        "name": "Kinetic Word Box",
        "description": "Clean sans-serif text where active word is encased in a dynamic glowing solid pill badge.",
        "category": "kinetic",
        "font_family": "Plus Jakarta Sans",
        "font_weight": "ExtraBold",
        "font_size": 34,
        "text_fill": "solid",
        "text_color": "#E2E8F0",
        "highlight_fill": "solid",
        "highlight_color": "#FFFFFF",
        "stroke": None,
        "shadow": {"color": "#000000", "blur": 8, "offset_x": 0, "offset_y": 2, "opacity": 0.5},
        "background": None,
        "active_word_badge": {
            "bg_color": "#FF0055",
            "border_radius": 8,
            "padding_x": 8,
            "padding_y": 4,
            "shadow": "0 4px 15px rgba(255,0,85,0.5)",
        },
        "position_y_pct": 78,
        "uppercase": False,
        "max_words_per_line": 3,
        "line_transition": "word_pop",
        "per_char_transform": None,
    },
    "neon_tube": {
        "id": "neon_tube",
        "name": "Neon Tube",
        "description": "Multi-layer cyber neon: hollow stroke + 3 outer glow passes in cyan & hot magenta.",
        "category": "neon",
        "font_family": "Montserrat",
        "font_weight": "Black",
        "font_size": 42,
        "text_fill": "solid",
        "text_color": "transparent",
        "highlight_fill": "solid",
        "highlight_color": "#FF007F",
        "stroke": {"color": "#00FFFF", "width": 2.2},
        "shadow": None,
        "glow_layers": [
            {"color": "#00FFFF", "blur": 4, "opacity": 1.0},
            {"color": "#00FFFF", "blur": 12, "opacity": 0.6},
            {"color": "#0088FF", "blur": 24, "opacity": 0.3},
        ],
        "background": None,
        "position_y_pct": 50,
        "uppercase": True,
        "max_words_per_line": 2,
        "line_transition": "word_pop",
        "per_char_transform": None,
    },
    "gradient_fill": {
        "id": "gradient_fill",
        "name": "Gradient Fill",
        "description": "Multi-stop linear gradient text with angle shift and specular shimmer on active words.",
        "category": "gradient",
        "font_family": "Poppins",
        "font_weight": "Bold",
        "font_size": 38,
        "text_fill": "gradient",
        "text_gradient": {
            "type": "linear",
            "angle": 135,
            "stops": [
                {"offset": 0.0, "color": "#6366F1"},
                {"offset": 0.5, "color": "#8B5CF6"},
                {"offset": 1.0, "color": "#EC4899"},
            ],
        },
        "highlight_fill": "gradient",
        "highlight_gradient": {
            "type": "linear",
            "angle": 45,
            "stops": [
                {"offset": 0.0, "color": "#F5576C"},
                {"offset": 1.0, "color": "#FF9A76"},
            ],
        },
        "stroke": None,
        "shadow": {"color": "#000000", "blur": 8, "offset_x": 0, "offset_y": 3, "opacity": 0.6},
        "background": None,
        "position_y_pct": 80,
        "uppercase": False,
        "max_words_per_line": 3,
        "line_transition": "word_pop",
        "per_char_transform": None,
    },
    "cinematic_slate": {
        "id": "cinematic_slate",
        "name": "Cinematic Slate",
        "description": "Muted dark tones with warm champagne gold highlight for documentary & high-end videos.",
        "category": "cinematic",
        "font_family": "Playfair Display",
        "font_weight": "Bold",
        "font_size": 36,
        "text_fill": "solid",
        "text_color": "#CBD5E1",
        "highlight_fill": "solid",
        "highlight_color": "#FCD34D",
        "stroke": None,
        "shadow": {"color": "#000000", "blur": 12, "offset_x": 0, "offset_y": 4, "opacity": 0.7},
        "background": None,
        "position_y_pct": 78,
        "uppercase": False,
        "max_words_per_line": 3,
        "line_transition": "word_pop",
        "per_char_transform": None,
    },
    "modern_mono": {
        "id": "modern_mono",
        "name": "Modern Mono",
        "description": "Clean monospace typography with cyber cyan active word punch for tech and educational clips.",
        "category": "tech",
        "font_family": "Space Grotesk",
        "font_weight": "Bold",
        "font_size": 34,
        "text_fill": "solid",
        "text_color": "#94A3B8",
        "highlight_fill": "solid",
        "highlight_color": "#06B6D4",
        "stroke": None,
        "shadow": {"color": "#000000", "blur": 8, "offset_x": 0, "offset_y": 2, "opacity": 0.6},
        "background": {
            "type": "pill",
            "bg_color": "#090D16",
            "bg_opacity": 0.8,
            "border_radius": 8,
            "border_color": "rgba(6,182,212,0.3)",
            "border_width": 1,
            "padding_x": 16,
            "padding_y": 8,
        },
        "position_y_pct": 80,
        "uppercase": True,
        "max_words_per_line": 3,
        "line_transition": "word_pop",
        "per_char_transform": None,
    },
    "bold_impact_stroke": {
        "id": "bold_impact_stroke",
        "name": "Bold Impact",
        "description": "Anton heavy shorts punch with solid 3.5px black stroke and electric yellow active word.",
        "category": "impact",
        "font_family": "Anton",
        "font_weight": "Bold",
        "font_size": 44,
        "text_fill": "solid",
        "text_color": "#FFFFFF",
        "highlight_fill": "solid",
        "highlight_color": "#FACC15",
        "stroke": {"color": "#000000", "width": 3.5},
        "shadow": {"color": "#000000", "blur": 14, "offset_x": 0, "offset_y": 4, "opacity": 0.85},
        "background": None,
        "position_y_pct": 78,
        "uppercase": True,
        "max_words_per_line": 2,
        "line_transition": "word_pop",
        "per_char_transform": None,
    },
    "dual_layer": {
        "id": "dual_layer",
        "name": "Dual Layer Depth",
        "description": "Blurred purple backlight shadow layer behind sharp white text on top for 3D depth.",
        "category": "depth",
        "font_family": "Outfit",
        "font_weight": "Bold",
        "font_size": 40,
        "text_fill": "solid",
        "text_color": "#FFFFFF",
        "highlight_fill": "solid",
        "highlight_color": "#FBBF24",
        "stroke": None,
        "shadow": None,
        "background": None,
        "text_layers": [
            {
                "role": "back",
                "color": "#7C3AED",
                "blur": 6,
                "scale": 1.08,
                "offset_x": 0,
                "offset_y": 4,
                "opacity": 0.7,
            },
            {
                "role": "front",
                "color": "#FFFFFF",
                "blur": 0,
                "scale": 1.0,
                "offset_x": 0,
                "offset_y": 0,
                "opacity": 1.0,
            },
        ],
        "position_y_pct": 76,
        "uppercase": False,
        "max_words_per_line": 3,
        "line_transition": "word_pop",
        "per_char_transform": None,
    },
    "retro_chrome": {
        "id": "retro_chrome",
        "name": "Retro Chrome",
        "description": "80s metallic chrome reflection gradient with gold highlight and hard drop shadow.",
        "category": "retro",
        "font_family": "Bebas Neue",
        "font_weight": "Bold",
        "font_size": 46,
        "text_fill": "gradient",
        "text_gradient": {
            "type": "linear",
            "angle": 180,
            "stops": [
                {"offset": 0.0, "color": "#2D2D2D"},
                {"offset": 0.3, "color": "#E8E8E8"},
                {"offset": 0.5, "color": "#FFFFFF"},
                {"offset": 0.7, "color": "#C0C0C0"},
                {"offset": 1.0, "color": "#4A4A4A"},
            ],
        },
        "highlight_fill": "gradient",
        "highlight_gradient": {
            "type": "linear",
            "angle": 180,
            "stops": [
                {"offset": 0.0, "color": "#FFD700"},
                {"offset": 0.5, "color": "#FFFFFF"},
                {"offset": 1.0, "color": "#FF8C00"},
            ],
        },
        "stroke": {"color": "#000000", "width": 2},
        "shadow": {"color": "#000000", "blur": 0, "offset_x": 4, "offset_y": 4, "opacity": 0.9},
        "background": None,
        "position_y_pct": 50,
        "uppercase": True,
        "max_words_per_line": 3,
        "line_transition": "word_pop",
        "per_char_transform": None,
    },
    "outline_stack": {
        "id": "outline_stack",
        "name": "Outline Stack",
        "description": "3D anaglyphic red and blue offset stroke outline stack without fill.",
        "category": "3d",
        "font_family": "Archivo Black",
        "font_weight": "Regular",
        "font_size": 42,
        "text_fill": "none",
        "text_color": "transparent",
        "highlight_fill": "solid",
        "highlight_color": "#FFFFFF",
        "stroke": None,
        "shadow": None,
        "background": None,
        "outline_layers": [
            {"color": "#FF0000", "width": 2.5, "offset_x": -2, "offset_y": -2, "opacity": 0.85},
            {"color": "#00FFFF", "width": 2.5, "offset_x": 2, "offset_y": 2, "opacity": 0.85},
        ],
        "position_y_pct": 50,
        "uppercase": True,
        "max_words_per_line": 2,
        "line_transition": "word_pop",
        "per_char_transform": None,
    },
}


def get_ffmpeg_style(style_id: str) -> dict:
    """Get FFmpeg style preset by ID. Returns classic_karaoke as default."""
    return FFMPEG_STYLES.get(style_id, FFMPEG_STYLES["classic_karaoke"])


def get_skia_style(style_id: str) -> dict:
    """Get Skia style preset by ID. Returns gradient_fill as default."""
    return SKIA_STYLES.get(style_id, SKIA_STYLES["gradient_fill"])


def list_ffmpeg_styles() -> list[dict]:
    """List all FFmpeg style presets (id, name, description, category)."""
    return [
        {"id": s["id"], "name": s["name"], "description": s["description"], "category": s["category"]}
        for s in FFMPEG_STYLES.values()
    ]


def list_skia_styles() -> list[dict]:
    """List all Skia style presets (id, name, description, category)."""
    return [
        {"id": s["id"], "name": s["name"], "description": s["description"], "category": s["category"]}
        for s in SKIA_STYLES.values()
    ]
