"""Subtitle style presets for FFmpeg and Skia engines.

Each style has a truly distinct visual identity — not just color/font swaps.
Differences: layout, animation mode, text transform, bg shape, positioning, effects.
"""

# ─── FFmpeg Subtitle Styles (drawtext-based) ──────────────────────────────────
# Each style produces fundamentally different visual output via drawtext filters.

FFMPEG_STYLES = {
    "classic_karaoke": {
        "id": "classic_karaoke",
        "name": "Classic Karaoke",
        "description": "Standard word-by-word highlight. Clean white text, active word turns yellow.",
        "category": "karaoke",
        "font_family": "Poppins",
        "font_weight": "Bold",
        "font_size": 38,
        "color": "#FFFFFF",
        "highlight_color": "#FFCC00",
        "stroke_color": "#000000",
        "stroke_width": 3,
        "shadow_color": "black@0.6",
        "shadow_x": 2,
        "shadow_y": 2,
        "background_opacity": 0.0,
        "background_color": "",
        "background_radius": 0,
        "position": "bottom",
        "padding_bottom": 120,
        "uppercase": False,
        "max_words_per_line": 3,
        "line_transition": "karaoke",
        "gradient_enabled": False,
        "gradient_colors": [],
    },
    "neon_glow": {
        "id": "neon_glow",
        "name": "Neon Glow",
        "description": "Glowing neon text on dark. Heavy border glow simulates neon tube effect.",
        "category": "glow",
        "font_family": "Montserrat",
        "font_weight": "Black",
        "font_size": 42,
        "color": "#00FFAA",
        "highlight_color": "#FF00FF",
        "stroke_color": "#00FFAA",
        "stroke_width": 6,
        "shadow_color": "#00FFAA@0.8",
        "shadow_x": 0,
        "shadow_y": 0,
        "background_opacity": 0.7,
        "background_color": "#000000",
        "background_radius": 0,
        "position": "center",
        "padding_bottom": 0,
        "uppercase": True,
        "max_words_per_line": 2,
        "line_transition": "word_pop",
        "gradient_enabled": False,
        "gradient_colors": [],
    },
    "typewriter_mono": {
        "id": "typewriter_mono",
        "name": "Typewriter",
        "description": "Monospace font, one word at a time center-screen. Minimal retro terminal look.",
        "category": "minimal",
        "font_family": "JetBrainsMono",
        "font_weight": "Regular",
        "font_size": 32,
        "color": "#00FF00",
        "highlight_color": "#FFFFFF",
        "stroke_color": "",
        "stroke_width": 0,
        "shadow_color": "",
        "shadow_x": 0,
        "shadow_y": 0,
        "background_opacity": 0.85,
        "background_color": "#0D0D0D",
        "background_radius": 0,
        "position": "center",
        "padding_bottom": 0,
        "uppercase": False,
        "max_words_per_line": 1,
        "line_transition": "word_pop",
        "gradient_enabled": False,
        "gradient_colors": [],
    },
    "bold_impact": {
        "id": "bold_impact",
        "name": "Bold Impact",
        "description": "Massive uppercase text, center screen. Impact-style with thick black outline.",
        "category": "impact",
        "font_family": "Anton",
        "font_weight": "Regular",
        "font_size": 64,
        "color": "#FFFFFF",
        "highlight_color": "#FF3333",
        "stroke_color": "#000000",
        "stroke_width": 5,
        "shadow_color": "black@0.9",
        "shadow_x": 3,
        "shadow_y": 3,
        "background_opacity": 0.0,
        "background_color": "",
        "background_radius": 0,
        "position": "center",
        "padding_bottom": 0,
        "uppercase": True,
        "max_words_per_line": 2,
        "line_transition": "word_pop",
        "gradient_enabled": False,
        "gradient_colors": [],
    },
    "pastel_bubble": {
        "id": "pastel_bubble",
        "name": "Pastel Bubble",
        "description": "Rounded pill background, pastel colors. Soft aesthetic look for lifestyle content.",
        "category": "aesthetic",
        "font_family": "Nunito",
        "font_weight": "Bold",
        "font_size": 30,
        "color": "#2D2D2D",
        "highlight_color": "#E91E63",
        "stroke_color": "",
        "stroke_width": 0,
        "shadow_color": "",
        "shadow_x": 0,
        "shadow_y": 0,
        "background_opacity": 0.92,
        "background_color": "#FFF0F5",
        "background_radius": 20,
        "position": "bottom",
        "padding_bottom": 140,
        "uppercase": False,
        "max_words_per_line": 4,
        "line_transition": "line_reveal",
        "gradient_enabled": False,
        "gradient_colors": [],
    },
    "cinematic_bar": {
        "id": "cinematic_bar",
        "name": "Cinematic Bar",
        "description": "Full-width dark bar at bottom. Uppercase condensed font. Film subtitle style.",
        "category": "cinematic",
        "font_family": "Oswald",
        "font_weight": "Medium",
        "font_size": 28,
        "color": "#E0E0E0",
        "highlight_color": "#FFD700",
        "stroke_color": "",
        "stroke_width": 0,
        "shadow_color": "",
        "shadow_x": 0,
        "shadow_y": 0,
        "background_opacity": 0.75,
        "background_color": "#1A1A1A",
        "background_radius": 0,
        "position": "bottom",
        "padding_bottom": 60,
        "uppercase": True,
        "max_words_per_line": 6,
        "line_transition": "line_reveal",
        "gradient_enabled": False,
        "gradient_colors": [],
    },
    "fire_emphasis": {
        "id": "fire_emphasis",
        "name": "Fire Emphasis",
        "description": "Big keyword pops in orange-red, small context words below. Energy/hype content.",
        "category": "emphasis",
        "font_family": "Bebas Neue",
        "font_weight": "Regular",
        "font_size": 36,
        "color": "#FFFFFF",
        "highlight_color": "#FF4500",
        "stroke_color": "#000000",
        "stroke_width": 4,
        "shadow_color": "#FF4500@0.5",
        "shadow_x": 0,
        "shadow_y": 4,
        "background_opacity": 0.0,
        "background_color": "",
        "background_radius": 0,
        "position": "bottom",
        "padding_bottom": 100,
        "uppercase": True,
        "max_words_per_line": 3,
        "line_transition": "emphasis",
        "gradient_enabled": False,
        "gradient_colors": [],
    },
    "glass_blur": {
        "id": "glass_blur",
        "name": "Glass Blur",
        "description": "Frosted glass background effect. White text on translucent blurred panel.",
        "category": "glass",
        "font_family": "Inter",
        "font_weight": "SemiBold",
        "font_size": 30,
        "color": "#FFFFFF",
        "highlight_color": "#60A5FA",
        "stroke_color": "",
        "stroke_width": 0,
        "shadow_color": "white@0.2",
        "shadow_x": 0,
        "shadow_y": 1,
        "background_opacity": 0.45,
        "background_color": "#FFFFFF",
        "background_radius": 16,
        "position": "bottom",
        "padding_bottom": 130,
        "uppercase": False,
        "max_words_per_line": 4,
        "line_transition": "karaoke",
        "gradient_enabled": False,
        "gradient_colors": [],
    },
    "street_graffiti": {
        "id": "street_graffiti",
        "name": "Street Graffiti",
        "description": "Tilted text, spray-paint aesthetic. Heavy shadow, raw urban vibe.",
        "category": "urban",
        "font_family": "Permanent Marker",
        "font_weight": "Regular",
        "font_size": 44,
        "color": "#FFEB3B",
        "highlight_color": "#FF1744",
        "stroke_color": "#000000",
        "stroke_width": 5,
        "shadow_color": "black@0.9",
        "shadow_x": 4,
        "shadow_y": 4,
        "background_opacity": 0.0,
        "background_color": "",
        "background_radius": 0,
        "position": "center",
        "padding_bottom": 0,
        "uppercase": True,
        "max_words_per_line": 2,
        "line_transition": "word_pop",
        "gradient_enabled": False,
        "gradient_colors": [],
    },
    "minimal_lower": {
        "id": "minimal_lower",
        "name": "Minimal Lower",
        "description": "Tiny text at very bottom. No effects, just clean lowercase. Documentary style.",
        "category": "minimal",
        "font_family": "IBM Plex Sans",
        "font_weight": "Regular",
        "font_size": 22,
        "color": "#CCCCCC",
        "highlight_color": "#FFFFFF",
        "stroke_color": "",
        "stroke_width": 0,
        "shadow_color": "black@0.4",
        "shadow_x": 0,
        "shadow_y": 1,
        "background_opacity": 0.0,
        "background_color": "",
        "background_radius": 0,
        "position": "bottom",
        "padding_bottom": 40,
        "uppercase": False,
        "max_words_per_line": 6,
        "line_transition": "line_reveal",
        "gradient_enabled": False,
        "gradient_colors": [],
    },
}

# ─── Skia Subtitle Styles (CanvasKit GPU-rendered) ────────────────────────────
# Skia supports: gradients, rounded rects, blur, glow, multi-color text, shadows.
# Each produces a PNG frame overlay composited onto video via FFmpeg.

SKIA_STYLES = {
    "gradient_wave": {
        "id": "gradient_wave",
        "name": "Gradient Wave",
        "description": "Text with horizontal gradient fill. Active word has different gradient direction.",
        "category": "gradient",
        "font_family": "Poppins",
        "font_weight": "Bold",
        "font_size": 40,
        "text_color": "#FFFFFF",
        "highlight_color": "#FF6B6B",
        "gradient_enabled": True,
        "gradient_type": "linear",
        "gradient_colors": ["#667EEA", "#764BA2"],
        "gradient_angle": 90,
        "highlight_gradient_colors": ["#F093FB", "#F5576C"],
        "bg_enabled": False,
        "bg_color": "",
        "bg_opacity": 0.0,
        "bg_radius": 0,
        "bg_padding": 0,
        "blur_radius": 0,
        "glow_enabled": False,
        "glow_color": "",
        "glow_radius": 0,
        "stroke_enabled": False,
        "stroke_color": "",
        "stroke_width": 0,
        "shadow_enabled": True,
        "shadow_color": "#000000",
        "shadow_blur": 8,
        "shadow_offset_x": 0,
        "shadow_offset_y": 3,
        "position": "bottom",
        "position_y_pct": 82,
        "uppercase": False,
        "max_words_per_line": 3,
        "line_transition": "word_pop",
    },
    "frosted_card": {
        "id": "frosted_card",
        "name": "Frosted Card",
        "description": "Text on frosted glass card with heavy blur bg. Rounded corners, slight shadow.",
        "category": "glass",
        "font_family": "Inter",
        "font_weight": "SemiBold",
        "font_size": 32,
        "text_color": "#FFFFFF",
        "highlight_color": "#38BDF8",
        "gradient_enabled": False,
        "gradient_type": "none",
        "gradient_colors": [],
        "gradient_angle": 0,
        "highlight_gradient_colors": [],
        "bg_enabled": True,
        "bg_color": "#1E293B",
        "bg_opacity": 0.65,
        "bg_radius": 24,
        "bg_padding": 20,
        "blur_radius": 20,
        "glow_enabled": False,
        "glow_color": "",
        "glow_radius": 0,
        "stroke_enabled": True,
        "stroke_color": "#FFFFFF",
        "stroke_width": 1,
        "shadow_enabled": True,
        "shadow_color": "#000000",
        "shadow_blur": 16,
        "shadow_offset_x": 0,
        "shadow_offset_y": 6,
        "position": "bottom",
        "position_y_pct": 78,
        "uppercase": False,
        "max_words_per_line": 4,
        "line_transition": "karaoke",
    },
    "neon_outline": {
        "id": "neon_outline",
        "name": "Neon Outline",
        "description": "Transparent text with colored neon stroke + outer glow. Dark background contrast.",
        "category": "neon",
        "font_family": "Montserrat",
        "font_weight": "Black",
        "font_size": 44,
        "text_color": "transparent",
        "highlight_color": "#FF00FF",
        "gradient_enabled": False,
        "gradient_type": "none",
        "gradient_colors": [],
        "gradient_angle": 0,
        "highlight_gradient_colors": [],
        "bg_enabled": False,
        "bg_color": "",
        "bg_opacity": 0.0,
        "bg_radius": 0,
        "bg_padding": 0,
        "blur_radius": 0,
        "glow_enabled": True,
        "glow_color": "#00FFFF",
        "glow_radius": 12,
        "stroke_enabled": True,
        "stroke_color": "#00FFFF",
        "stroke_width": 3,
        "shadow_enabled": False,
        "shadow_color": "",
        "shadow_blur": 0,
        "shadow_offset_x": 0,
        "shadow_offset_y": 0,
        "position": "center",
        "position_y_pct": 50,
        "uppercase": True,
        "max_words_per_line": 2,
        "line_transition": "word_pop",
    },
    "candy_pill": {
        "id": "candy_pill",
        "name": "Candy Pill",
        "description": "Each word in its own pill-shaped badge with vibrant bg. Stacked horizontally.",
        "category": "badge",
        "font_family": "Nunito",
        "font_weight": "ExtraBold",
        "font_size": 28,
        "text_color": "#FFFFFF",
        "highlight_color": "#FFFFFF",
        "gradient_enabled": True,
        "gradient_type": "per_word",
        "gradient_colors": ["#FF6B6B", "#FFA502", "#7BED9F", "#70A1FF", "#A855F7"],
        "gradient_angle": 0,
        "highlight_gradient_colors": ["#FF0844", "#FFB199"],
        "bg_enabled": True,
        "bg_color": "per_word",
        "bg_opacity": 0.95,
        "bg_radius": 50,
        "bg_padding": 14,
        "blur_radius": 0,
        "glow_enabled": False,
        "glow_color": "",
        "glow_radius": 0,
        "stroke_enabled": False,
        "stroke_color": "",
        "stroke_width": 0,
        "shadow_enabled": True,
        "shadow_color": "#000000",
        "shadow_blur": 6,
        "shadow_offset_x": 0,
        "shadow_offset_y": 3,
        "position": "bottom",
        "position_y_pct": 80,
        "uppercase": False,
        "max_words_per_line": 3,
        "line_transition": "word_pop",
    },
    "dark_elegance": {
        "id": "dark_elegance",
        "name": "Dark Elegance",
        "description": "Serif font, dark semi-transparent wide bar. Gold accent on active word. Premium feel.",
        "category": "premium",
        "font_family": "Playfair Display",
        "font_weight": "Bold",
        "font_size": 34,
        "text_color": "#F5F5F5",
        "highlight_color": "#D4AF37",
        "gradient_enabled": False,
        "gradient_type": "none",
        "gradient_colors": [],
        "gradient_angle": 0,
        "highlight_gradient_colors": [],
        "bg_enabled": True,
        "bg_color": "#0A0A0A",
        "bg_opacity": 0.82,
        "bg_radius": 4,
        "bg_padding": 16,
        "blur_radius": 0,
        "glow_enabled": False,
        "glow_color": "",
        "glow_radius": 0,
        "stroke_enabled": False,
        "stroke_color": "",
        "stroke_width": 0,
        "shadow_enabled": True,
        "shadow_color": "#D4AF37",
        "shadow_blur": 4,
        "shadow_offset_x": 0,
        "shadow_offset_y": 0,
        "position": "bottom",
        "position_y_pct": 85,
        "uppercase": False,
        "max_words_per_line": 5,
        "line_transition": "line_reveal",
    },
    "retro_vhs": {
        "id": "retro_vhs",
        "name": "Retro VHS",
        "description": "VHS/CRT aesthetic: scan lines, chromatic offset, monospace. Glitch vibe.",
        "category": "retro",
        "font_family": "VT323",
        "font_weight": "Regular",
        "font_size": 36,
        "text_color": "#FFFFFF",
        "highlight_color": "#FF0000",
        "gradient_enabled": False,
        "gradient_type": "none",
        "gradient_colors": [],
        "gradient_angle": 0,
        "highlight_gradient_colors": [],
        "bg_enabled": True,
        "bg_color": "#000000",
        "bg_opacity": 0.6,
        "bg_radius": 0,
        "bg_padding": 8,
        "blur_radius": 0,
        "glow_enabled": True,
        "glow_color": "#00FF00",
        "glow_radius": 3,
        "stroke_enabled": False,
        "stroke_color": "",
        "stroke_width": 0,
        "shadow_enabled": True,
        "shadow_color": "#FF0000",
        "shadow_blur": 0,
        "shadow_offset_x": 2,
        "shadow_offset_y": 0,
        "position": "bottom",
        "position_y_pct": 75,
        "uppercase": True,
        "max_words_per_line": 3,
        "line_transition": "word_pop",
    },
    "aurora_glow": {
        "id": "aurora_glow",
        "name": "Aurora Glow",
        "description": "Multi-color radial gradient glow behind text. Ethereal/cosmic vibe.",
        "category": "cosmic",
        "font_family": "Quicksand",
        "font_weight": "Bold",
        "font_size": 36,
        "text_color": "#FFFFFF",
        "highlight_color": "#E0AAFF",
        "gradient_enabled": True,
        "gradient_type": "radial",
        "gradient_colors": ["#7400B8", "#6930C3", "#5390D9", "#48BFE3", "#72EFDD"],
        "gradient_angle": 0,
        "highlight_gradient_colors": ["#E0AAFF", "#C77DFF"],
        "bg_enabled": False,
        "bg_color": "",
        "bg_opacity": 0.0,
        "bg_radius": 0,
        "bg_padding": 0,
        "blur_radius": 0,
        "glow_enabled": True,
        "glow_color": "#7400B8",
        "glow_radius": 20,
        "stroke_enabled": False,
        "stroke_color": "",
        "stroke_width": 0,
        "shadow_enabled": True,
        "shadow_color": "#48BFE3",
        "shadow_blur": 12,
        "shadow_offset_x": 0,
        "shadow_offset_y": 0,
        "position": "center",
        "position_y_pct": 50,
        "uppercase": False,
        "max_words_per_line": 3,
        "line_transition": "karaoke",
    },
    "comic_burst": {
        "id": "comic_burst",
        "name": "Comic Burst",
        "description": "Comic book style: bold outlined text, star-burst bg shape, rotation on active word.",
        "category": "fun",
        "font_family": "Bangers",
        "font_weight": "Regular",
        "font_size": 48,
        "text_color": "#FFFFFF",
        "highlight_color": "#FFD700",
        "gradient_enabled": False,
        "gradient_type": "none",
        "gradient_colors": [],
        "gradient_angle": 0,
        "highlight_gradient_colors": [],
        "bg_enabled": True,
        "bg_color": "#FF1744",
        "bg_opacity": 0.95,
        "bg_radius": 8,
        "bg_padding": 16,
        "blur_radius": 0,
        "glow_enabled": False,
        "glow_color": "",
        "glow_radius": 0,
        "stroke_enabled": True,
        "stroke_color": "#000000",
        "stroke_width": 4,
        "shadow_enabled": True,
        "shadow_color": "#000000",
        "shadow_blur": 0,
        "shadow_offset_x": 4,
        "shadow_offset_y": 4,
        "position": "center",
        "position_y_pct": 45,
        "uppercase": True,
        "max_words_per_line": 2,
        "line_transition": "word_pop",
    },
    "split_duo": {
        "id": "split_duo",
        "name": "Split Duo",
        "description": "Two-line layout: top line small context, bottom line BIG keyword. Split emphasis.",
        "category": "split",
        "font_family": "Outfit",
        "font_weight": "Bold",
        "font_size": 32,
        "text_color": "#94A3B8",
        "highlight_color": "#FFFFFF",
        "gradient_enabled": True,
        "gradient_type": "vertical",
        "gradient_colors": ["#F8FAFC", "#CBD5E1"],
        "gradient_angle": 180,
        "highlight_gradient_colors": ["#FFFFFF", "#E2E8F0"],
        "bg_enabled": False,
        "bg_color": "",
        "bg_opacity": 0.0,
        "bg_radius": 0,
        "bg_padding": 0,
        "blur_radius": 0,
        "glow_enabled": False,
        "glow_color": "",
        "glow_radius": 0,
        "stroke_enabled": True,
        "stroke_color": "#1E293B",
        "stroke_width": 2,
        "shadow_enabled": True,
        "shadow_color": "#000000",
        "shadow_blur": 10,
        "shadow_offset_x": 0,
        "shadow_offset_y": 4,
        "position": "bottom",
        "position_y_pct": 75,
        "uppercase": False,
        "max_words_per_line": 3,
        "line_transition": "emphasis",
    },
    "clean_sans": {
        "id": "clean_sans",
        "name": "Clean Sans",
        "description": "Ultra-clean white text, no effects. Thin stroke only. Minimalist content creator.",
        "category": "minimal",
        "font_family": "DM Sans",
        "font_weight": "Medium",
        "font_size": 30,
        "text_color": "#FFFFFF",
        "highlight_color": "#10B981",
        "gradient_enabled": False,
        "gradient_type": "none",
        "gradient_colors": [],
        "gradient_angle": 0,
        "highlight_gradient_colors": [],
        "bg_enabled": False,
        "bg_color": "",
        "bg_opacity": 0.0,
        "bg_radius": 0,
        "bg_padding": 0,
        "blur_radius": 0,
        "glow_enabled": False,
        "glow_color": "",
        "glow_radius": 0,
        "stroke_enabled": True,
        "stroke_color": "#000000",
        "stroke_width": 2,
        "shadow_enabled": False,
        "shadow_color": "",
        "shadow_blur": 0,
        "shadow_offset_x": 0,
        "shadow_offset_y": 0,
        "position": "bottom",
        "position_y_pct": 82,
        "uppercase": False,
        "max_words_per_line": 4,
        "line_transition": "karaoke",
    },
}


def get_ffmpeg_style(style_id: str) -> dict:
    """Get FFmpeg style preset by ID. Returns classic_karaoke as default."""
    return FFMPEG_STYLES.get(style_id, FFMPEG_STYLES["classic_karaoke"])


def get_skia_style(style_id: str) -> dict:
    """Get Skia style preset by ID. Returns gradient_wave as default."""
    return SKIA_STYLES.get(style_id, SKIA_STYLES["gradient_wave"])


def list_ffmpeg_styles() -> list[dict]:
    """List all FFmpeg style presets (id, name, description, category)."""
    return [
        {"id": s["id"], "name": s["name"], "description": s["description"], "category": s["category"]}
        for s in FFMPEG_STYLES.values()
    ]


def list_skia_styles() -> list[dict]:
    """List all Skia style presets (id, name, description, category)."""
    return [
        {"id": s["id"], "name": s["name"], "description": s["description"], "category": s["category"]}
        for s in SKIA_STYLES.values()
    ]
