"""Subtitle style presets for FFmpeg and Skia engines.

Each style has a truly distinct visual identity — not just color/font swaps.
Differences: layout, animation mode, text transform, bg shape, positioning, effects.
"""

# ─── FFmpeg Subtitle Styles (drawtext-based) ──────────────────────────────────
# Each style produces fundamentally different visual output via drawtext filters.

FFMPEG_STYLES = {
    "classic_karaoke": {
        "id": "classic_karaoke",
        "name": "Classic Karaoke",
        "description": "Standard word-by-word highlight. Clean white text, active word turns yellow.",
        "category": "karaoke",
        "font_family": "Poppins",
        "font_weight": "Bold",
        "font_size": 38,
        "color": "#FFFFFF",
        "highlight_color": "#FFCC00",
        "stroke_color": "#000000",
        "stroke_width": 3,
        "shadow_color": "black@0.6",
        "shadow_x": 2,
        "shadow_y": 2,
        "background_opacity": 0.0,
        "background_color": "",
        "background_radius": 0,
        "position": "bottom",
        "padding_bottom": 120,
        "uppercase": False,
        "max_words_per_line": 3,
        "line_transition": "karaoke",
        "gradient_enabled": False,
        "gradient_colors": [],
    },
    "neon_glow": {
        "id": "neon_glow",
        "name": "Neon Glow",
        "description": "Glowing neon text on dark. Heavy border glow simulates neon tube effect.",
        "category": "glow",
        "font_family": "Montserrat",
        "font_weight": "Black",
        "font_size": 42,
        "color": "#00FFAA",
        "highlight_color": "#FF00FF",
        "stroke_color": "#00FFAA",
        "stroke_width": 6,
        "shadow_color": "#00FFAA@0.8",
        "shadow_x": 0,
        "shadow_y": 0,
        "background_opacity": 0.7,
        "background_color": "#000000",
        "background_radius": 0,
        "position": "center",
        "padding_bottom": 0,
        "uppercase": True,
        "max_words_per_line": 2,
        "line_transition": "word_pop",
        "gradient_enabled": False,
        "gradient_colors": [],
    },
    "typewriter_mono": {
        "id": "typewriter_mono",
        "name": "Typewriter",
        "description": "Monospace font, one word at a time center-screen. Minimal retro terminal look.",
        "category": "minimal",
        "font_family": "JetBrainsMono",
        "font_weight": "Regular",
        "font_size": 32,
        "color": "#00FF00",
        "highlight_color": "#FFFFFF",
        "stroke_color": "",
        "stroke_width": 0,
        "shadow_color": "",
        "shadow_x": 0,
        "shadow_y": 0,
        "background_opacity": 0.85,
        "background_color": "#0D0D0D",
        "background_radius": 0,
        "position": "center",
        "padding_bottom": 0,
        "uppercase": False,
        "max_words_per_line": 1,
        "line_transition": "word_pop",
        "gradient_enabled": False,
        "gradient_colors": [],
    },
    "bold_impact": {
        "id": "bold_impact",
        "name": "Bold Impact",
        "description": "Massive uppercase text, center screen. Impact-style with thick black outline.",
        "category": "impact",
        "font_family": "Anton",
        "font_weight": "Regular",
        "font_size": 64,
        "color": "#FFFFFF",
        "highlight_color": "#FF3333",
        "stroke_color": "#000000",
        "stroke_width": 5,
        "shadow_color": "black@0.9",
        "shadow_x": 3,
        "shadow_y": 3,
        "background_opacity": 0.0,
        "background_color": "",
        "background_radius": 0,
        "position": "center",
        "padding_bottom": 0,
        "uppercase": True,
        "max_words_per_line": 2,
        "line_transition": "word_pop",
        "gradient_enabled": False,
        "gradient_colors": [],
    },
    "pastel_bubble": {
        "id": "pastel_bubble",
        "name": "Pastel Bubble",
        "description": "Rounded pill background, pastel colors. Soft aesthetic look for lifestyle content.",
        "category": "aesthetic",
        "font_family": "Nunito",
        "font_weight": "Bold",
        "font_size": 30,
        "color": "#2D2D2D",
        "highlight_color": "#E91E63",
        "stroke_color": "",
        "stroke_width": 0,
        "shadow_color": "",
        "shadow_x": 0,
        "shadow_y": 0,
        "background_opacity": 0.92,
        "background_color": "#FFF0F5",
        "background_radius": 20,
        "position": "bottom",
        "padding_bottom": 140,
        "uppercase": False,
        "max_words_per_line": 4,
        "line_transition": "line_reveal",
        "gradient_enabled": False,
        "gradient_colors": [],
    },
    "cinematic_bar": {
        "id": "cinematic_bar",
        "name": "Cinematic Bar",
        "description": "Full-width dark bar at bottom. Uppercase condensed font. Film subtitle style.",
        "category": "cinematic",
        "font_family": "Oswald",
        "font_weight": "Medium",
        "font_size": 28,
        "color": "#E0E0E0",
        "highlight_color": "#FFD700",
        "stroke_color": "",
        "stroke_width": 0,
        "shadow_color": "",
        "shadow_x": 0,
        "shadow_y": 0,
        "background_opacity": 0.75,
        "background_color": "#1A1A1A",
        "background_radius": 0,
        "position": "bottom",
        "padding_bottom": 60,
        "uppercase": True,
        "max_words_per_line": 6,
        "line_transition": "line_reveal",
        "gradient_enabled": False,
        "gradient_colors": [],
    },
    "fire_emphasis": {
        "id": "fire_emphasis",
        "name": "Fire Emphasis",
        "description": "Big keyword pops in orange-red, small context words below. Energy/hype content.",
        "category": "emphasis",
        "font_family": "Bebas Neue",
        "font_weight": "Regular",
        "font_size": 36,
        "color": "#FFFFFF",
        "highlight_color": "#FF4500",
        "stroke_color": "#000000",
        "stroke_width": 4,
        "shadow_color": "#FF4500@0.5",
        "shadow_x": 0,
        "shadow_y": 4,
        "background_opacity": 0.0,
        "background_color": "",
        "background_radius": 0,
        "position": "bottom",
        "padding_bottom": 100,
        "uppercase": True,
        "max_words_per_line": 3,
        "line_transition": "emphasis",
        "gradient_enabled": False,
        "gradient_colors": [],
    },
    "glass_blur": {
        "id": "glass_blur",
        "name": "Glass Blur",
        "description": "Frosted glass background effect. White text on translucent blurred panel.",
        "category": "glass",
        "font_family": "Inter",
        "font_weight": "SemiBold",
        "font_size": 30,
        "color": "#FFFFFF",
        "highlight_color": "#60A5FA",
        "stroke_color": "",
        "stroke_width": 0,
        "shadow_color": "white@0.2",
        "shadow_x": 0,
        "shadow_y": 1,
        "background_opacity": 0.45,
        "background_color": "#FFFFFF",
        "background_radius": 16,
        "position": "bottom",
        "padding_bottom": 130,
        "uppercase": False,
        "max_words_per_line": 4,
        "line_transition": "karaoke",
        "gradient_enabled": False,
        "gradient_colors": [],
    },
    "street_graffiti": {
        "id": "street_graffiti",
        "name": "Street Graffiti",
        "description": "Tilted text, spray-paint aesthetic. Heavy shadow, raw urban vibe.",
        "category": "urban",
        "font_family": "Permanent Marker",
        "font_weight": "Regular",
        "font_size": 44,
        "color": "#FFEB3B",
        "highlight_color": "#FF1744",
        "stroke_color": "#000000",
        "stroke_width": 5,
        "shadow_color": "black@0.9",
        "shadow_x": 4,
        "shadow_y": 4,
        "background_opacity": 0.0,
        "background_color": "",
        "background_radius": 0,
        "position": "center",
        "padding_bottom": 0,
        "uppercase": True,
        "max_words_per_line": 2,
        "line_transition": "word_pop",
        "gradient_enabled": False,
        "gradient_colors": [],
    },
    "minimal_lower": {
        "id": "minimal_lower",
        "name": "Minimal Lower",
        "description": "Tiny text at very bottom. No effects, just clean lowercase. Documentary style.",
        "category": "minimal",
        "font_family": "IBM Plex Sans",
        "font_weight": "Regular",
        "font_size": 22,
        "color": "#CCCCCC",
        "highlight_color": "#FFFFFF",
        "stroke_color": "",
        "stroke_width": 0,
        "shadow_color": "black@0.4",
        "shadow_x": 0,
        "shadow_y": 1,
        "background_opacity": 0.0,
        "background_color": "",
        "background_radius": 0,
        "position": "bottom",
        "padding_bottom": 40,
        "uppercase": False,
        "max_words_per_line": 6,
        "line_transition": "line_reveal",
        "gradient_enabled": False,
        "gradient_colors": [],
    },
}

# ─── Skia Subtitle Styles (CanvasKit GPU-rendered) ────────────────────────────
# Skia supports: gradients, rounded rects, blur, glow, multi-color text, shadows.
# Each produces a PNG frame overlay composited onto video via FFmpeg.

SKIA_STYLES = {
    "gradient_fill": {
        "id": "gradient_fill",
        "name": "Gradient Fill",
        "description": "Text filled with multi-stop linear gradient. Each word shifts gradient angle on highlight.",
        "category": "gradient",
        # Skia-exclusive: per-glyph gradient shader fill (impossible in FFmpeg drawtext)
        "font_family": "Poppins",
        "font_weight": "Bold",
        "font_size": 42,
        "text_fill": "gradient",  # gradient | solid | pattern
        "text_gradient": {
            "type": "linear",
            "angle": 135,
            "stops": [
                {"offset": 0.0, "color": "#667EEA"},
                {"offset": 0.5, "color": "#764BA2"},
                {"offset": 1.0, "color": "#F093FB"},
            ],
        },
        "highlight_fill": "gradient",
        "highlight_gradient": {
            "type": "linear",
            "angle": 45,
            "stops": [
                {"offset": 0.0, "color": "#F5576C"},
                {"offset": 1.0, "color": "#FF9A76"},
            ],
        },
        "stroke": None,
        "shadow": {"color": "#000000", "blur": 8, "offset_x": 0, "offset_y": 3, "opacity": 0.6},
        "background": None,
        "position_y_pct": 80,
        "uppercase": False,
        "max_words_per_line": 3,
        "line_transition": "word_pop",
        "per_char_transform": None,
    },
    "glassmorphism": {
        "id": "glassmorphism",
        "name": "Glassmorphism",
        "description": "Real frosted glass: backdrop blur + semi-transparent rounded card + inner border glow.",
        "category": "glass",
        # Skia-exclusive: backdrop blur (ImageFilter), inner border, real transparency compositing
        "font_family": "Inter",
        "font_weight": "SemiBold",
        "font_size": 32,
        "text_fill": "solid",
        "text_color": "#FFFFFF",
        "highlight_fill": "solid",
        "highlight_color": "#38BDF8",
        "stroke": None,
        "shadow": None,
        "background": {
            "type": "glassmorphism",
            "blur_radius": 24,  # backdrop blur sigma
            "bg_color": "#1E293B",
            "bg_opacity": 0.35,
            "border_radius": 28,
            "border_color": "#FFFFFF",
            "border_opacity": 0.15,
            "border_width": 1.5,
            "padding_x": 28,
            "padding_y": 16,
            "inner_shadow": {"color": "#FFFFFF", "opacity": 0.05, "blur": 4, "offset_y": -1},
        },
        "position_y_pct": 78,
        "uppercase": False,
        "max_words_per_line": 4,
        "line_transition": "karaoke",
        "per_char_transform": None,
    },
    "neon_tube": {
        "id": "neon_tube",
        "name": "Neon Tube",
        "description": "Multi-layer neon: inner fill + colored stroke + 3 outer glow passes at different radii.",
        "category": "neon",
        # Skia-exclusive: multiple MaskFilter blur passes stacked (3-layer glow impossible in FFmpeg)
        "font_family": "Montserrat",
        "font_weight": "Black",
        "font_size": 46,
        "text_fill": "solid",
        "text_color": "transparent",  # hollow text, neon is all about the glow
        "highlight_fill": "solid",
        "highlight_color": "#FF00FF",
        "stroke": {"color": "#00FFFF", "width": 2.5},
        "shadow": None,
        "glow_layers": [
            {"color": "#00FFFF", "blur": 4, "opacity": 1.0},   # tight inner glow
            {"color": "#00FFFF", "blur": 12, "opacity": 0.6},  # medium spread
            {"color": "#0088FF", "blur": 28, "opacity": 0.3},  # wide ambient
        ],
        "background": None,
        "position_y_pct": 50,
        "uppercase": True,
        "max_words_per_line": 2,
        "line_transition": "word_pop",
        "per_char_transform": None,
    },
    "per_word_badge": {
        "id": "per_word_badge",
        "name": "Per-Word Badge",
        "description": "Each word in its own pill-shaped badge with unique color from palette. Stacked with gap.",
        "category": "badge",
        # Skia-exclusive: per-word independent RoundRect backgrounds with rotation + palette cycling
        "font_family": "Nunito",
        "font_weight": "ExtraBold",
        "font_size": 28,
        "text_fill": "solid",
        "text_color": "#FFFFFF",
        "highlight_fill": "solid",
        "highlight_color": "#FFFFFF",
        "stroke": None,
        "shadow": {"color": "#000000", "blur": 6, "offset_x": 0, "offset_y": 3, "opacity": 0.4},
        "background": {
            "type": "per_word_badge",
            "border_radius": 50,  # pill shape
            "padding_x": 16,
            "padding_y": 10,
            "word_gap": 8,
            "color_palette": ["#FF6B6B", "#FFA502", "#7BED9F", "#70A1FF", "#A855F7", "#F472B6"],
            "highlight_color": "#FF0844",
            "rotation_range": [-3, 3],  # subtle random tilt per badge (degrees)
        },
        "position_y_pct": 78,
        "uppercase": False,
        "max_words_per_line": 3,
        "line_transition": "word_pop",
        "per_char_transform": None,
    },
    "path_wave": {
        "id": "path_wave",
        "name": "Path Wave",
        "description": "Text rendered along a sine-wave bezier path. Each word undulates vertically.",
        "category": "kinetic",
        # Skia-exclusive: drawTextOnPath with bezier curve (completely impossible in FFmpeg)
        "font_family": "Fredoka",
        "font_weight": "Bold",
        "font_size": 38,
        "text_fill": "solid",
        "text_color": "#FFFFFF",
        "highlight_fill": "gradient",
        "highlight_gradient": {
            "type": "linear",
            "angle": 0,
            "stops": [
                {"offset": 0.0, "color": "#F97316"},
                {"offset": 1.0, "color": "#EF4444"},
            ],
        },
        "stroke": {"color": "#000000", "width": 3},
        "shadow": {"color": "#000000", "blur": 6, "offset_x": 0, "offset_y": 2, "opacity": 0.7},
        "background": None,
        "text_path": {
            "type": "sine_wave",
            "amplitude": 12,   # pixels up/down
            "frequency": 0.8,  # waves per word
        },
        "position_y_pct": 75,
        "uppercase": False,
        "max_words_per_line": 4,
        "line_transition": "karaoke",
        "per_char_transform": None,
    },
    "char_stagger": {
        "id": "char_stagger",
        "name": "Char Stagger",
        "description": "Each character rendered individually with staggered vertical offset + opacity. Kinetic type.",
        "category": "kinetic",
        # Skia-exclusive: per-character independent transform matrix (position, scale, rotation, opacity)
        "font_family": "Space Grotesk",
        "font_weight": "Bold",
        "font_size": 40,
        "text_fill": "solid",
        "text_color": "#E2E8F0",
        "highlight_fill": "solid",
        "highlight_color": "#FFFFFF",
        "stroke": {"color": "#0F172A", "width": 2},
        "shadow": None,
        "background": None,
        "position_y_pct": 80,
        "uppercase": True,
        "max_words_per_line": 2,
        "line_transition": "word_pop",
        "per_char_transform": {
            "type": "stagger_y",
            "offset_range": [-6, 6],     # px vertical scatter
            "rotation_range": [-4, 4],   # degrees
            "scale_range": [0.95, 1.05],
            "opacity_range": [0.7, 1.0],
            "stagger_delay_ms": 30,      # per-char appearance delay
        },
    },
    "dual_layer": {
        "id": "dual_layer",
        "name": "Dual Layer",
        "description": "Text rendered twice: large blurred color layer behind + sharp white layer on top. Depth effect.",
        "category": "depth",
        # Skia-exclusive: multi-pass text rendering with independent blur + offset per pass
        "font_family": "Outfit",
        "font_weight": "Bold",
        "font_size": 44,
        "text_fill": "solid",
        "text_color": "#FFFFFF",
        "highlight_fill": "solid",
        "highlight_color": "#FBBF24",
        "stroke": None,
        "shadow": None,
        "background": None,
        "text_layers": [
            {
                "role": "back",
                "color": "#7C3AED",
                "blur": 6,
                "scale": 1.08,
                "offset_x": 0,
                "offset_y": 4,
                "opacity": 0.7,
            },
            {
                "role": "front",
                "color": "#FFFFFF",
                "blur": 0,
                "scale": 1.0,
                "offset_x": 0,
                "offset_y": 0,
                "opacity": 1.0,
            },
        ],
        "position_y_pct": 76,
        "uppercase": False,
        "max_words_per_line": 3,
        "line_transition": "word_pop",
        "per_char_transform": None,
    },
    "mask_reveal": {
        "id": "mask_reveal",
        "name": "Mask Reveal",
        "description": "Text acts as clip mask revealing a gradient/pattern underneath. Background shows through text shape.",
        "category": "mask",
        # Skia-exclusive: text as clip path (SrcIn/DstIn compositing) revealing image/gradient beneath
        "font_family": "Anton",
        "font_weight": "Regular",
        "font_size": 56,
        "text_fill": "mask",  # text shape clips the fill_source below
        "fill_source": {
            "type": "animated_gradient",
            "colors": ["#FF0080", "#7928CA", "#FF0080"],
            "angle_start": 0,
            "angle_speed": 45,  # degrees per second rotation
        },
        "highlight_fill": "mask",
        "highlight_source": {
            "type": "solid_pulse",
            "color": "#FFFFFF",
            "pulse_opacity": [0.8, 1.0],
            "pulse_speed_ms": 400,
        },
        "stroke": {"color": "#000000", "width": 1.5},
        "shadow": {"color": "#FF0080", "blur": 16, "offset_x": 0, "offset_y": 0, "opacity": 0.5},
        "background": None,
        "position_y_pct": 50,
        "uppercase": True,
        "max_words_per_line": 2,
        "line_transition": "word_pop",
        "per_char_transform": None,
    },
    "retro_chrome": {
        "id": "retro_chrome",
        "name": "Retro Chrome",
        "description": "80s chrome text: vertical gradient (dark→white→dark) simulating metallic reflection + hard shadow.",
        "category": "retro",
        # Skia-exclusive: precise multi-stop vertical gradient within text glyphs + specular highlight band
        "font_family": "Bebas Neue",
        "font_weight": "Regular",
        "font_size": 52,
        "text_fill": "gradient",
        "text_gradient": {
            "type": "linear",
            "angle": 180,  # top to bottom
            "stops": [
                {"offset": 0.0, "color": "#2D2D2D"},
                {"offset": 0.3, "color": "#E8E8E8"},
                {"offset": 0.5, "color": "#FFFFFF"},  # specular band
                {"offset": 0.7, "color": "#C0C0C0"},
                {"offset": 1.0, "color": "#4A4A4A"},
            ],
        },
        "highlight_fill": "gradient",
        "highlight_gradient": {
            "type": "linear",
            "angle": 180,
            "stops": [
                {"offset": 0.0, "color": "#FFD700"},
                {"offset": 0.5, "color": "#FFFFFF"},
                {"offset": 1.0, "color": "#FF8C00"},
            ],
        },
        "stroke": {"color": "#000000", "width": 2},
        "shadow": {"color": "#000000", "blur": 0, "offset_x": 4, "offset_y": 4, "opacity": 0.9},
        "background": None,
        "position_y_pct": 50,
        "uppercase": True,
        "max_words_per_line": 3,
        "line_transition": "word_pop",
        "per_char_transform": None,
    },
    "outline_stack": {
        "id": "outline_stack",
        "name": "Outline Stack",
        "description": "3 offset copies of text outline (no fill) in different colors, creating a 3D stack/anaglyphic look.",
        "category": "3d",
        # Skia-exclusive: multiple stroke-only text passes at different offsets + colors
        "font_family": "Archivo Black",
        "font_weight": "Regular",
        "font_size": 48,
        "text_fill": "none",  # no fill — outline only
        "text_color": "transparent",
        "highlight_fill": "solid",
        "highlight_color": "#FFFFFF",
        "stroke": None,  # handled by outline_layers
        "shadow": None,
        "background": None,
        "outline_layers": [
            {"color": "#FF0000", "width": 3, "offset_x": -3, "offset_y": -3, "opacity": 0.8},
            {"color": "#00FF00", "width": 3, "offset_x": 0, "offset_y": 0, "opacity": 0.8},
            {"color": "#0000FF", "width": 3, "offset_x": 3, "offset_y": 3, "opacity": 0.8},
        ],
        "position_y_pct": 50,
        "uppercase": True,
        "max_words_per_line": 2,
        "line_transition": "word_pop",
        "per_char_transform": None,
    },
    "clean_editorial": {
        "id": "clean_editorial",
        "name": "Clean Editorial",
        "description": "Minimalist Swiss typography with a sleek slate pill and crisp word-by-word active highlight.",
        "category": "clean",
        "font_family": "Inter",
        "font_weight": "SemiBold",
        "font_size": 34,
        "text_fill": "solid",
        "text_color": "#D1D5DB",
        "highlight_fill": "solid",
        "highlight_color": "#38BDF8",
        "stroke": None,
        "shadow": {"color": "#000000", "blur": 8, "offset_x": 0, "offset_y": 2, "opacity": 0.45},
        "background": {
            "type": "pill",
            "bg_color": "#0F172A",
            "bg_opacity": 0.65,
            "border_radius": 14,
            "border_color": "rgba(255,255,255,0.15)",
            "border_width": 1,
            "padding_x": 18,
            "padding_y": 10,
        },
        "position_y_pct": 80,
        "uppercase": False,
        "max_words_per_line": 4,
        "line_transition": "karaoke",
        "per_char_transform": None,
    },
    "nordic_minimal": {
        "id": "nordic_minimal",
        "name": "Nordic Minimal",
        "description": "Understated Scandinavian aesthetic: muted slate to crisp white with smooth line underline tracking.",
        "category": "clean",
        "font_family": "Outfit",
        "font_weight": "Medium",
        "font_size": 32,
        "text_fill": "solid",
        "text_color": "#94A3B8",
        "highlight_fill": "solid",
        "highlight_color": "#F8FAFC",
        "stroke": None,
        "shadow": {"color": "#000000", "blur": 6, "offset_x": 0, "offset_y": 2, "opacity": 0.5},
        "background": None,
        "position_y_pct": 82,
        "uppercase": False,
        "max_words_per_line": 5,
        "line_transition": "line_reveal",
        "per_char_transform": None,
    },
    "podcast_pro": {
        "id": "podcast_pro",
        "name": "Podcast Pro",
        "description": "Dialogue-optimized floating dark capsule with emerald active speaker highlight.",
        "category": "clean",
        "font_family": "Plus Jakarta Sans",
        "font_weight": "Bold",
        "font_size": 32,
        "text_fill": "solid",
        "text_color": "#E2E8F0",
        "highlight_fill": "solid",
        "highlight_color": "#10B981",
        "stroke": None,
        "shadow": {"color": "#000000", "blur": 10, "offset_x": 0, "offset_y": 3, "opacity": 0.6},
        "background": {
            "type": "pill",
            "bg_color": "#18181B",
            "bg_opacity": 0.82,
            "border_radius": 20,
            "border_color": "rgba(255,255,255,0.12)",
            "border_width": 1.2,
            "padding_x": 20,
            "padding_y": 10,
        },
        "position_y_pct": 78,
        "uppercase": False,
        "max_words_per_line": 4,
        "line_transition": "karaoke",
        "per_char_transform": None,
    },
    "cinematic_slate": {
        "id": "cinematic_slate",
        "name": "Cinematic Slate",
        "description": "Muted dark tones with warm champagne gold highlight for documentary & high-end videos.",
        "category": "clean",
        "font_family": "Playfair Display",
        "font_weight": "Bold",
        "font_size": 36,
        "text_fill": "solid",
        "text_color": "#CBD5E1",
        "highlight_fill": "solid",
        "highlight_color": "#FCD34D",
        "stroke": None,
        "shadow": {"color": "#000000", "blur": 12, "offset_x": 0, "offset_y": 4, "opacity": 0.7},
        "background": None,
        "position_y_pct": 78,
        "uppercase": False,
        "max_words_per_line": 3,
        "line_transition": "word_pop",
        "per_char_transform": None,
    },
    "modern_mono": {
        "id": "modern_mono",
        "name": "Modern Mono",
        "description": "Clean monospace typography with cyber cyan active word punch for tech and educational clips.",
        "category": "clean",
        "font_family": "Space Grotesk",
        "font_weight": "Bold",
        "font_size": 34,
        "text_fill": "solid",
        "text_color": "#94A3B8",
        "highlight_fill": "solid",
        "highlight_color": "#06B6D4",
        "stroke": None,
        "shadow": {"color": "#000000", "blur": 8, "offset_x": 0, "offset_y": 2, "opacity": 0.6},
        "background": {
            "type": "pill",
            "bg_color": "#090D16",
            "bg_opacity": 0.75,
            "border_radius": 10,
            "border_color": "rgba(6,182,212,0.3)",
            "border_width": 1,
            "padding_x": 16,
            "padding_y": 8,
        },
        "position_y_pct": 80,
        "uppercase": True,
        "max_words_per_line": 3,
        "line_transition": "word_pop",
        "per_char_transform": None,
    },
    "soft_shadow_lead": {
        "id": "soft_shadow_lead",
        "name": "Soft Shadow Lead",
        "description": "Floating clean typography with zero background clutter, maximum readability drop shadow.",
        "category": "clean",
        "font_family": "Inter",
        "font_weight": "ExtraBold",
        "font_size": 36,
        "text_fill": "solid",
        "text_color": "#FFFFFF",
        "highlight_fill": "solid",
        "highlight_color": "#FBBF24",
        "stroke": {"color": "#000000", "width": 2},
        "shadow": {"color": "#000000", "blur": 16, "offset_x": 0, "offset_y": 4, "opacity": 0.85},
        "background": None,
        "position_y_pct": 78,
        "uppercase": False,
        "max_words_per_line": 3,
        "line_transition": "word_pop",
        "per_char_transform": None,
    },
}


def get_ffmpeg_style(style_id: str) -> dict:
    """Get FFmpeg style preset by ID. Returns classic_karaoke as default."""
    return FFMPEG_STYLES.get(style_id, FFMPEG_STYLES["classic_karaoke"])


def get_skia_style(style_id: str) -> dict:
    """Get Skia style preset by ID. Returns gradient_fill as default."""
    return SKIA_STYLES.get(style_id, SKIA_STYLES["gradient_fill"])


def list_ffmpeg_styles() -> list[dict]:
    """List all FFmpeg style presets (id, name, description, category)."""
    return [
        {"id": s["id"], "name": s["name"], "description": s["description"], "category": s["category"]}
        for s in FFMPEG_STYLES.values()
    ]


def list_skia_styles() -> list[dict]:
    """List all Skia style presets (id, name, description, category)."""
    return [
        {"id": s["id"], "name": s["name"], "description": s["description"], "category": s["category"]}
        for s in SKIA_STYLES.values()
    ]
